

package org.jetbrains.kotlin.compiler.plugin.template.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.compiler.plugin.template.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("koin-compiler-plugin/testData/box")
@TestDataPath("$PROJECT_ROOT")
public class JvmBoxTestGenerated extends AbstractJvmBoxTest {
  private void run(String fileName) {
    runTest("koin-compiler-plugin/testData/box/" + fileName);
  }

  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("koin-compiler-plugin/testData/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Nested
  @TestMetadata("koin-compiler-plugin/testData/box/annotations")
  @TestDataPath("$PROJECT_ROOT")
  public class Annotations {
    private void run(String fileName) {
      runTest("koin-compiler-plugin/testData/box/annotations/" + fileName);
    }

    @Test
    public void testAllFilesPresentInAnnotations() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("koin-compiler-plugin/testData/box/annotations"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("factory_class.kt")
    public void testFactory_class() {
      run("factory_class.kt");
    }

    @Test
    @TestMetadata("singleton_class.kt")
    public void testSingleton_class() {
      run("singleton_class.kt");
    }
  }

  @Nested
  @TestMetadata("koin-compiler-plugin/testData/box/bindings")
  @TestDataPath("$PROJECT_ROOT")
  public class Bindings {
    private void run(String fileName) {
      runTest("koin-compiler-plugin/testData/box/bindings/" + fileName);
    }

    @Test
    public void testAllFilesPresentInBindings() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("koin-compiler-plugin/testData/box/bindings"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("auto_interface_binding.kt")
    public void testAuto_interface_binding() {
      run("auto_interface_binding.kt");
    }

    @Test
    @TestMetadata("delegation_no_autobind.kt")
    public void testDelegation_no_autobind() {
      run("delegation_no_autobind.kt");
    }

    @Test
    @TestMetadata("provider_function_binds.kt")
    public void testProvider_function_binds() {
      run("provider_function_binds.kt");
    }
  }

  @Nested
  @TestMetadata("koin-compiler-plugin/testData/box/dsl")
  @TestDataPath("$PROJECT_ROOT")
  public class Dsl {
    private void run(String fileName) {
      runTest("koin-compiler-plugin/testData/box/dsl/" + fileName);
    }

    @Test
    public void testAllFilesPresentInDsl() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("koin-compiler-plugin/testData/box/dsl"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("arrow_bind_non_koin.kt")
    public void testArrow_bind_non_koin() {
      run("arrow_bind_non_koin.kt");
    }

    @Test
    @TestMetadata("create_constructor.kt")
    public void testCreate_constructor() {
      run("create_constructor.kt");
    }

    @Test
    @TestMetadata("factory_basic.kt")
    public void testFactory_basic() {
      run("factory_basic.kt");
    }

    @Test
    @TestMetadata("scoped_basic.kt")
    public void testScoped_basic() {
      run("scoped_basic.kt");
    }

    @Test
    @TestMetadata("single_basic.kt")
    public void testSingle_basic() {
      run("single_basic.kt");
    }

    @Test
    @TestMetadata("single_with_default_value.kt")
    public void testSingle_with_default_value() {
      run("single_with_default_value.kt");
    }

    @Test
    @TestMetadata("single_with_dependency.kt")
    public void testSingle_with_dependency() {
      run("single_with_dependency.kt");
    }

    @Test
    @TestMetadata("single_with_lazy.kt")
    public void testSingle_with_lazy() {
      run("single_with_lazy.kt");
    }

    @Test
    @TestMetadata("single_with_nullable.kt")
    public void testSingle_with_nullable() {
      run("single_with_nullable.kt");
    }
  }

  @Nested
  @TestMetadata("koin-compiler-plugin/testData/box/modules")
  @TestDataPath("$PROJECT_ROOT")
  public class Modules {
    private void run(String fileName) {
      runTest("koin-compiler-plugin/testData/box/modules/" + fileName);
    }

    @Test
    public void testAllFilesPresentInModules() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("koin-compiler-plugin/testData/box/modules"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("component_scan_basic.kt")
    public void testComponent_scan_basic() {
      run("component_scan_basic.kt");
    }

    @Test
    @TestMetadata("module_extension.kt")
    public void testModule_extension() {
      run("module_extension.kt");
    }

    @Test
    @TestMetadata("module_with_functions.kt")
    public void testModule_with_functions() {
      run("module_with_functions.kt");
    }
  }

  @Nested
  @TestMetadata("koin-compiler-plugin/testData/box/monitor")
  @TestDataPath("$PROJECT_ROOT")
  public class Monitor {
    private void run(String fileName) {
      runTest("koin-compiler-plugin/testData/box/monitor/" + fileName);
    }

    @Test
    public void testAllFilesPresentInMonitor() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("koin-compiler-plugin/testData/box/monitor"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("monitor_class.kt")
    public void testMonitor_class() {
      run("monitor_class.kt");
    }

    @Test
    @TestMetadata("monitor_function.kt")
    public void testMonitor_function() {
      run("monitor_function.kt");
    }
  }

  @Nested
  @TestMetadata("koin-compiler-plugin/testData/box/params")
  @TestDataPath("$PROJECT_ROOT")
  public class Params {
    private void run(String fileName) {
      runTest("koin-compiler-plugin/testData/box/params/" + fileName);
    }

    @Test
    public void testAllFilesPresentInParams() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("koin-compiler-plugin/testData/box/params"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("injected_param.kt")
    public void testInjected_param() {
      run("injected_param.kt");
    }

    @Test
    @TestMetadata("lazy_injection.kt")
    public void testLazy_injection() {
      run("lazy_injection.kt");
    }

    @Test
    @TestMetadata("property_basic.kt")
    public void testProperty_basic() {
      run("property_basic.kt");
    }
  }

  @Nested
  @TestMetadata("koin-compiler-plugin/testData/box/qualifiers")
  @TestDataPath("$PROJECT_ROOT")
  public class Qualifiers {
    private void run(String fileName) {
      runTest("koin-compiler-plugin/testData/box/qualifiers/" + fileName);
    }

    @Test
    public void testAllFilesPresentInQualifiers() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("koin-compiler-plugin/testData/box/qualifiers"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("custom_qualifier_type.kt")
    public void testCustom_qualifier_type() {
      run("custom_qualifier_type.kt");
    }

    @Test
    @TestMetadata("named_on_class.kt")
    public void testNamed_on_class() {
      run("named_on_class.kt");
    }

    @Test
    @TestMetadata("named_on_parameter.kt")
    public void testNamed_on_parameter() {
      run("named_on_parameter.kt");
    }

    @Test
    @TestMetadata("qualifier_type.kt")
    public void testQualifier_type() {
      run("qualifier_type.kt");
    }
  }

  @Nested
  @TestMetadata("koin-compiler-plugin/testData/box/safety")
  @TestDataPath("$PROJECT_ROOT")
  public class Safety {
    private void run(String fileName) {
      runTest("koin-compiler-plugin/testData/box/safety/" + fileName);
    }

    @Test
    public void testAllFilesPresentInSafety() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("koin-compiler-plugin/testData/box/safety"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("callsite_hint_module_prefix.kt")
    public void testCallsite_hint_module_prefix() {
      run("callsite_hint_module_prefix.kt");
    }

    @Test
    @TestMetadata("complete_graph.kt")
    public void testComplete_graph() {
      run("complete_graph.kt");
    }

    @Test
    @TestMetadata("configuration_group.kt")
    public void testConfiguration_group() {
      run("configuration_group.kt");
    }

    @Test
    @TestMetadata("default_value_ok.kt")
    public void testDefault_value_ok() {
      run("default_value_ok.kt");
    }

    @Test
    @TestMetadata("dsl_create_function.kt")
    public void testDsl_create_function() {
      run("dsl_create_function.kt");
    }

    @Test
    @TestMetadata("dsl_injected_param_d006.kt")
    public void testDsl_injected_param_d006() {
      run("dsl_injected_param_d006.kt");
    }

    @Test
    @TestMetadata("dsl_module_includes.kt")
    public void testDsl_module_includes() {
      run("dsl_module_includes.kt");
    }

    @Test
    @TestMetadata("dsl_transitive_includes.kt")
    public void testDsl_transitive_includes() {
      run("dsl_transitive_includes.kt");
    }

    @Test
    @TestMetadata("generic_dsl_type_no_crash.kt")
    public void testGeneric_dsl_type_no_crash() {
      run("generic_dsl_type_no_crash.kt");
    }

    @Test
    @TestMetadata("injected_param_ok.kt")
    public void testInjected_param_ok() {
      run("injected_param_ok.kt");
    }

    @Test
    @TestMetadata("injected_param_unit_qualifier_collision.kt")
    public void testInjected_param_unit_qualifier_collision() {
      run("injected_param_unit_qualifier_collision.kt");
    }

    @Test
    @TestMetadata("lazy_valid.kt")
    public void testLazy_valid() {
      run("lazy_valid.kt");
    }

    @Test
    @TestMetadata("list_ok.kt")
    public void testList_ok() {
      run("list_ok.kt");
    }

    @Test
    @TestMetadata("module_includes_chain.kt")
    public void testModule_includes_chain() {
      run("module_includes_chain.kt");
    }

    @Test
    @TestMetadata("module_includes_visible.kt")
    public void testModule_includes_visible() {
      run("module_includes_visible.kt");
    }

    @Test
    @TestMetadata("nullable_ok.kt")
    public void testNullable_ok() {
      run("nullable_ok.kt");
    }

    @Test
    @TestMetadata("property_value_ok.kt")
    public void testProperty_value_ok() {
      run("property_value_ok.kt");
    }

    @Test
    @TestMetadata("provided_param_dsl_ok.kt")
    public void testProvided_param_dsl_ok() {
      run("provided_param_dsl_ok.kt");
    }

    @Test
    @TestMetadata("provided_param_ok.kt")
    public void testProvided_param_ok() {
      run("provided_param_ok.kt");
    }

    @Test
    @TestMetadata("provided_type_ok.kt")
    public void testProvided_type_ok() {
      run("provided_type_ok.kt");
    }

    @Test
    @TestMetadata("qualified_function_cross_module.kt")
    public void testQualified_function_cross_module() {
      run("qualified_function_cross_module.kt");
    }

    @Test
    @TestMetadata("qualifier_cross_module.kt")
    public void testQualifier_cross_module() {
      run("qualifier_cross_module.kt");
    }

    @Test
    @TestMetadata("qualifier_cross_module_type.kt")
    public void testQualifier_cross_module_type() {
      run("qualifier_cross_module_type.kt");
    }

    @Test
    @TestMetadata("qualifier_dotted_name.kt")
    public void testQualifier_dotted_name() {
      run("qualifier_dotted_name.kt");
    }

    @Test
    @TestMetadata("qualifier_match.kt")
    public void testQualifier_match() {
      run("qualifier_match.kt");
    }

    @Test
    @TestMetadata("scope_id_ok.kt")
    public void testScope_id_ok() {
      run("scope_id_ok.kt");
    }

    @Test
    @TestMetadata("scope_param_dsl_ok.kt")
    public void testScope_param_dsl_ok() {
      run("scope_param_dsl_ok.kt");
    }

    @Test
    @TestMetadata("scope_param_ok.kt")
    public void testScope_param_ok() {
      run("scope_param_ok.kt");
    }

    @Test
    @TestMetadata("scoped_visibility.kt")
    public void testScoped_visibility() {
      run("scoped_visibility.kt");
    }

    @Test
    @TestMetadata("startkoin_full_graph.kt")
    public void testStartkoin_full_graph() {
      run("startkoin_full_graph.kt");
    }

    @Test
    @TestMetadata("toplevel_function_ok.kt")
    public void testToplevel_function_ok() {
      run("toplevel_function_ok.kt");
    }
  }

  @Nested
  @TestMetadata("koin-compiler-plugin/testData/box/scopes")
  @TestDataPath("$PROJECT_ROOT")
  public class Scopes {
    private void run(String fileName) {
      runTest("koin-compiler-plugin/testData/box/scopes/" + fileName);
    }

    @Test
    public void testAllFilesPresentInScopes() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("koin-compiler-plugin/testData/box/scopes"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("scope_class.kt")
    public void testScope_class() {
      run("scope_class.kt");
    }
  }

  @Nested
  @TestMetadata("koin-compiler-plugin/testData/box/startkoin")
  @TestDataPath("$PROJECT_ROOT")
  public class Startkoin {
    private void run(String fileName) {
      runTest("koin-compiler-plugin/testData/box/startkoin/" + fileName);
    }

    @Test
    public void testAllFilesPresentInStartkoin() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("koin-compiler-plugin/testData/box/startkoin"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("configuration_discovery.kt")
    public void testConfiguration_discovery() {
      run("configuration_discovery.kt");
    }

    @Test
    @TestMetadata("explicit_modules_override_configuration.kt")
    public void testExplicit_modules_override_configuration() {
      run("explicit_modules_override_configuration.kt");
    }

    @Test
    @TestMetadata("koin_application.kt")
    public void testKoin_application() {
      run("koin_application.kt");
    }

    @Test
    @TestMetadata("multiple_modules.kt")
    public void testMultiple_modules() {
      run("multiple_modules.kt");
    }

    @Test
    @TestMetadata("startkoin_basic.kt")
    public void testStartkoin_basic() {
      run("startkoin_basic.kt");
    }
  }

  @Nested
  @TestMetadata("koin-compiler-plugin/testData/box/toplevel")
  @TestDataPath("$PROJECT_ROOT")
  public class Toplevel {
    private void run(String fileName) {
      runTest("koin-compiler-plugin/testData/box/toplevel/" + fileName);
    }

    @Test
    public void testAllFilesPresentInToplevel() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("koin-compiler-plugin/testData/box/toplevel"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("qualified_unit_singletons.kt")
    public void testQualified_unit_singletons() {
      run("qualified_unit_singletons.kt");
    }

    @Test
    @TestMetadata("singleton_function.kt")
    public void testSingleton_function() {
      run("singleton_function.kt");
    }
  }
}
