

package org.jetbrains.kotlin.compiler.plugin.template.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.compiler.plugin.template.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("koin-compiler-plugin/testData/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class JvmDiagnosticTestGenerated extends AbstractJvmDiagnosticTest {
  private void run(String fileName) {
    runTest("koin-compiler-plugin/testData/diagnostics/" + fileName);
  }

  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("koin-compiler-plugin/testData/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("call_site_param_arity_mismatch.kt")
  public void testCall_site_param_arity_mismatch() {
    run("call_site_param_arity_mismatch.kt");
  }

  @Test
  @TestMetadata("call_site_param_dsl_missing_d006.kt")
  public void testCall_site_param_dsl_missing_d006() {
    run("call_site_param_dsl_missing_d006.kt");
  }

  @Test
  @TestMetadata("call_site_param_missing_d006.kt")
  public void testCall_site_param_missing_d006() {
    run("call_site_param_missing_d006.kt");
  }

  @Test
  @TestMetadata("call_site_param_no_injected_no_d006.kt")
  public void testCall_site_param_no_injected_no_d006() {
    run("call_site_param_no_injected_no_d006.kt");
  }

  @Test
  @TestMetadata("call_site_param_nullable_ok.kt")
  public void testCall_site_param_nullable_ok() {
    run("call_site_param_nullable_ok.kt");
  }

  @Test
  @TestMetadata("call_site_param_ok.kt")
  public void testCall_site_param_ok() {
    run("call_site_param_ok.kt");
  }

  @Test
  @TestMetadata("call_site_param_type_mismatch.kt")
  public void testCall_site_param_type_mismatch() {
    run("call_site_param_type_mismatch.kt");
  }

  @Test
  @TestMetadata("circular_dependency_broken_by_lazy.kt")
  public void testCircular_dependency_broken_by_lazy() {
    run("circular_dependency_broken_by_lazy.kt");
  }

  @Test
  @TestMetadata("circular_dependency_direct.kt")
  public void testCircular_dependency_direct() {
    run("circular_dependency_direct.kt");
  }

  @Test
  @TestMetadata("circular_dependency_transitive.kt")
  public void testCircular_dependency_transitive() {
    run("circular_dependency_transitive.kt");
  }

  @Test
  @TestMetadata("configuration_label_mismatch.kt")
  public void testConfiguration_label_mismatch() {
    run("configuration_label_mismatch.kt");
  }

  @Test
  @TestMetadata("dsl_module_not_loaded.kt")
  public void testDsl_module_not_loaded() {
    run("dsl_module_not_loaded.kt");
  }

  @Test
  @TestMetadata("dsl_module_unreachable.kt")
  public void testDsl_module_unreachable() {
    run("dsl_module_unreachable.kt");
  }

  @Test
  @TestMetadata("lazy_missing.kt")
  public void testLazy_missing() {
    run("lazy_missing.kt");
  }

  @Test
  @TestMetadata("missing_dependency.kt")
  public void testMissing_dependency() {
    run("missing_dependency.kt");
  }

  @Test
  @TestMetadata("missing_viewmodel_artifact.kt")
  public void testMissing_viewmodel_artifact() {
    run("missing_viewmodel_artifact.kt");
  }

  @Test
  @TestMetadata("missing_worker_artifact.kt")
  public void testMissing_worker_artifact() {
    run("missing_worker_artifact.kt");
  }

  @Test
  @TestMetadata("provided_missing.kt")
  public void testProvided_missing() {
    run("provided_missing.kt");
  }

  @Test
  @TestMetadata("qualifier_mismatch.kt")
  public void testQualifier_mismatch() {
    run("qualifier_mismatch.kt");
  }

  @Test
  @TestMetadata("scoped_cross_scope.kt")
  public void testScoped_cross_scope() {
    run("scoped_cross_scope.kt");
  }

  @Test
  @TestMetadata("startkoin_missing.kt")
  public void testStartkoin_missing() {
    run("startkoin_missing.kt");
  }
}
